### ISSUE TITLE
[Question] Does rudr schedule containers of multi-container component on the same pod?

### ISSUE THREAD

**Issue by gunniwho** [oam-dev/rudr#453] opened 2019-11-08 08:13 UTC
I already asked a similar question in the OAM spec (https://github.com/oam-dev/spec/issues/252) where I was told that there are no guarantees about this behavior in the spec but that rudr does work this way for _server_ workloads. So I have follow up questions:
a) is this a documented behavior of rudr (i.e. something that you can count on or just an implementation detail that could change) and 
b) why is this only for _server_ workloads?

**Comment by technosophos** [comment] 2019-11-08 16:00
If a Component declares multiple containers, Rudr will start all of those containers on the same Pod. My intention, when writing the spec, was for this to be the case in Kubernetes.

This is the intended behavior. If other workloads are not doing that, it is a bug.

**Comment by resouer** [comment] 2019-11-08 19:53
More details:

 > a) is this a documented behavior of rudr (i.e. something that you can count on or just an implementation detail that could change) and

It's by design, so you could count it. We could probably add a section in doc like "Kubernetes Application Patterns and The Design of Rudr" :-)

> b) why is this only for server workloads?

_Server_ workload of Rudr is just referred as an example since your previous issue was raised in Spec repo. In the context of this repo, the design above applies to all workloads.

**Comment by gunniwho** [comment] 2019-11-08 22:19
Thank you, that's great. It would in any case be great if it said somewhere in the ComponentSchematic docs that the containers of a component are scheduled on the same pod :)

**Comment by wonderflow** [comment] 2019-11-09 01:09
Yeah, we could add this to docs

**Comment by suhuruli** [comment] 2019-11-11 17:23
@gunniwho, closing this since your PR got merged. Thanks for the issue and following up with a fix. Please re-open if you think I closed this too early.

**Closed by suhuruli** 2019-11-11 17:23 UTC
Labels: Status: Good-First-Issue, Type: Docs, Type: Question
