### ISSUE TITLE
ApplicationConfiguration does not create any pods

### ISSUE THREAD

**Issue by isurulucky** [oam-dev/rudr#441] opened 2019-10-31 13:11 UTC
Hi, 
This is my ApplicationConfiguration:
```json
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  annotations:
    description: Hello World App
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"core.oam.dev/v1alpha1","kind":"ApplicationConfiguration","metadata":{"annotations":{"description":"Hello World App","version":"v1.0.0"},"name":"hello-app","namespace":"default"},"spec":{"components":[{"componentName":"helloworld","instanceName":"myhelloapp","traits":[{"name":"ingress","parameterValues":[{"name":"hostname","value":"helloworld.com"},{"name":"path","value":"/"},{"name":"service_port","value":9090}]}]}],"variables":null}}
    version: v1.0.0
  creationTimestamp: "2019-10-31T11:43:07Z"
  generation: 1
  name: hello-app
  namespace: default
  resourceVersion: "46968"
  selfLink: /apis/core.oam.dev/v1alpha1/namespaces/default/applicationconfigurations/hello-app
  uid: 9b583805-fbd3-11e9-a7ed-0800274110f1
spec:
  components:
  - componentName: helloworld
    instanceName: myhelloapp
    traits:
    - name: ingress
      parameterValues:
      - name: hostname
        value: helloworld.com
      - name: path
        value: /
      - name: service_port
        value: 9090
  variables: null
```

This refers to an already deployed component `helloworld`. However deploying this ApplicationConfiguration does not do anything. Am using rudr version v1.0.0-alpha.1. 

One thing I noted is That the `status` is missing in when I do `kubectl get configurations hello-app -o yaml`. 

Is there anything wrong with what I have done? Or is this a known issue?

**Comment by suhuruli** [comment] 2019-10-31 21:44
Hey! 

This is not a known issue and requires some investigation. @wonderflow or @technosophos. Just to confirm rudr is running right? 

Can you do a `kubectl logs <rudr_pod>` and paste the output?

**Comment by isurulucky** [comment] 2019-11-01 00:42
Hi @suhuruli, 
Yes the rudr pod is running and following are the logs - 

```
[2019-10-31T11:18:26Z INFO  rudr] starting server
[2019-10-31T11:18:26Z INFO  rudr] Watcher is running
[2019-10-31T11:18:26Z INFO  rudr] Health server is running on 0.0.0.0:8080
```

**Comment by wonderflow** [comment] 2019-11-01 02:49
If you could paste your `helloworld` component yaml, then I will be able to reproduce your problem.

**Comment by isurulucky** [comment] 2019-11-01 04:04
@wonderflow Please find component and Application yamls:

apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: helloworld
spec:
  name: helloworld
  workloadType: core.oam.dev/v1alpha1.Server
  containers:
    - name: foo
      image: isurulucky/hello-world-api:0.0.1
      ports:
        - type: tcp
          containerPort: 9090
          name: http
---
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: hello-app
  annotations:
    version: v1.0.0
    description: "Hello World App"
spec:
  variables:
  components:
  - componentName: helloworld
    instanceName: myhelloapp
    traits:
    - name: ingress
      parameterValues:
      - name: hostname
        value: helloworld.com
      - name: path
        value: /
      - name: service_port
        value: 9090

**Comment by wonderflow** [comment] 2019-11-01 10:55
I have reproduced  this problem by installing rudr using helm charts.

But I can't reproduce this issue in my develop environment by starting rudr use `make run`.

What's more weird is when I checkout my branch to `v1.0.0-alpha.1`, deploy the latest image with chart in `v1.0.0-alpha.1`, it works OK again. Then I revert all changes in `charts/rudr/` from master branch, the problem still there.

So I didn't figure out what's wrong now, but I guess the problem must hide in rudr charts

**Comment by technosophos** [comment] 2019-11-01 22:24
I will check if anything changed recently in the chart. But assuming that it is running in the correct namespace and with the proper RBACs, there's nothing I know of that could cause this particular issue.

**Comment by technosophos** [comment] 2019-11-02 00:21
I installed Rudr like this: `helm install rudr ./charts/rudr --set logLevel="rudr=debug"`. That provides much more verbose output. What I am seeing in the logs is:

```
[2019-11-01T23:52:17Z INFO  rudr] starting server
[2019-11-01T23:52:17Z INFO  rudr] Watcher is running
[2019-11-01T23:52:17Z INFO  rudr] Health server is running on 0.0.0.0:8080
[2019-11-01T23:52:22Z DEBUG rudr] health check
[2019-11-01T23:52:25Z DEBUG rudr] health check
[2019-11-01T23:52:27Z DEBUG rudr] loop
[2019-11-01T23:52:32Z DEBUG rudr] health check
[2019-11-01T23:52:35Z DEBUG rudr] health check
[2019-11-01T23:52:37Z DEBUG rudr] loop
```

When I create and delete new configs, they are not picked up by the event loop (though I see the loop running). That means that the listener is not getting events from the Kubernetes API.

So there are two possibilities:

1. Something changed in the most recent Kube/k8s-openapi, and we're not correctly connecting to the event stream when in-cluster
2. Something is not right with the ServiceAccount/ClusterRole/ClusterRoleBinding

To test things, I decided to delete a CRD to see if the `precheck_crds` function worked:

```
[2019-11-02T00:11:16Z INFO  rudr] starting server
[2019-11-02T00:11:16Z ERROR rudr] Error prechecking CRDs: ApiError NotFound ("customresourcedefinitions.apiextensions.k8s.io \"scopes.core.oam.dev\" not found")
Error: ErrorMessage { msg: "Missing CRD scopes" }
```

What we can learn from that is that right configuration file was loaded, and the Rudr does indeed have permissions to read the CRDs.

So for some reason we're not getting events on the event stream. I still suspect the ClusterRole as being the most likely culprit, but I will need to keep debugging to figure it out.

**Comment by wonderflow** [comment] 2019-11-04 07:28
I find it could be blocked by calling K8s API, but when I try to add some debug log and rebuild the image, the problem just disappear.

Now `oamdev/rudr:latest` is new image I build today I can't reproduce this issue now, while `oamdev/rudr-amb64:latest` is still old one and issue can be reproduced.

**Comment by isurulucky** [comment] 2019-11-05 07:57
Thanks @wonderflow and @technosophos. Will give this a try.

**Comment by technosophos** [comment] 2019-11-05 18:55
So do we need to just cut a new `alpha.2` release with the latest build?

**Comment by noelbundick** [comment] 2019-11-07 20:05
Hitting this as well with the same symptoms. Nothing mentioned here unblocks me thus far. 

I've tried updating the deployment to

* `oamdev/rudr:latest` (default)
* `oamdev/rudr-amd64:latest`
* `oamdev/rudr:v1.0.0-alpha.1`

rudr logs:

```
Loading...[2019-11-07T07:30:43Z INFO  rudr] starting server
[2019-11-07T07:30:43Z INFO  rudr] Watcher is running
[2019-11-07T07:30:43Z INFO  rudr] Health server is running on 0.0.0.0:8080
[2019-11-07T07:30:46Z DEBUG rudr] health check
[2019-11-07T07:30:47Z DEBUG rudr] health check
[2019-11-07T07:30:53Z DEBUG rudr] loop
[2019-11-07T07:30:56Z DEBUG rudr] health check
[2019-11-07T07:30:57Z DEBUG rudr] health check
[2019-11-07T07:31:03Z DEBUG rudr] loop
[2019-11-07T07:31:06Z DEBUG rudr] health check
```

Environment info:

* Docker Desktop for Windows:  `2.1.04` (39773 / stable)
* kind `v0.5.1`
  * k8s `1.15.3`

I suspect my issues may be related to the k8s config created by `kind` - I've encountered other odd errors, such as Helm 2 failing on initial install due to ServiceAccount / ClusterRole issues. It's unfortunate that rudr fails without any additional log information on a critical failure like this

Happy to troubleshoot, open PR's, etc. to resolve - really looking forward to kicking the tires

**Comment by noelbundick** [comment] 2019-11-07 21:10
@technosophos latest image (digest 843eaf3f938b) on Docker Hub shows `rudr::instigator` log entries and creates a Pod. Thanks!

**Comment by technosophos** [comment] 2019-11-08 15:57
Sorry... I mean to post a message here asking you to try, but got sidetracked. Thanks for finding and testing. Can I mark this as closed now?

**Comment by wonderflow** [comment] 2019-11-09 01:06
Maybe we should prepare to release `alpha.2`, it's better to release next week, before kubecon.

**Comment by showbiz2k** [comment] 2019-11-10 14:09
Should this be working with the latest image on docker hub?  I deployed using the helm chart from the master branch of the repo and targeting :latest but no pods are created for my app configuration (and the yaml for the app configuration doesn't include status information).

When I inspect the yaml for the rudr pod I see this for container status:
 containerStatuses:
  - containerID: docker://e966a37efd2bd52b2713d066b92a1c03a8e8292df3b457492368d7d7e03c3a5a          
    image: oamdev/rudr:latest
    imageID: docker-pullable://oamdev/rudr@sha256:a702e88e5fbfa168e52ffd5abec893c0d9a6b011c46cb7

I see the latest hash on docker hub as sha256:fd3b018424cc40df164983a26e9762ac378e19c8c0a53dfdd00085d567175c49

Maybe I'm not getting the proper container image?

**Comment by wonderflow** [comment] 2019-11-11 04:11
I have figured out what really happened. It's my fault.

I used to test nightly build in my own GitHub Repo using same account with rudr. It didn't cause any problem because two github repo  created the same docker image together. And everytime rudr using more time, so image created by rudr can cover images created by my repo.

Unfortunately, nightly build failed several days ago so images was again replaced by old versions triggerd by my repo.

Now I have delete account and disable action in my repo and build the latest images manually.

@showbiz2k  Hope you could give it retry, thanks!

**Comment by showbiz2k** [comment] 2019-11-11 12:23
Thanks @wonderflow.  I re-installed the rudr helm package and now I'm able to deploy new app configuration and pods are getting created.  Looking forward to experimenting with rudr!

**Comment by wonderflow** [comment] 2019-11-12 03:08
I have split github action job. Let me close this issue. If anyone still find same issue, please comment or open a new one.

**Closed by wonderflow** 2019-11-12 03:08 UTC
Labels: Type: Bug
