### ISSUE TITLE
Changes to manual-scaler in ApplicationConfiguration do not trigger change of replicas

### ISSUE THREAD

**Issue by jiria** [oam-dev/rudr#344] opened 2019-10-14 21:50 UTC
Changing `manual-scaler` `replicaCount` from `1` to `2` does not update `deployment` replica count. The following lines are output from the `scylla` pod. This is based on the latest nightly image.
```
[2019-10-14T21:41:13Z INFO  scylla::instigator] UID: a7687b7f-eeca-11e9-8522-dca63207ff04
[2019-10-14T21:41:13Z INFO  scylla::instigator] Looking up foo-app
[2019-10-14T21:41:13Z INFO  scylla::instigator] Adding component foo-worker
[2019-10-14T21:41:13Z INFO  scylla::schematic::component] Looking for image pull secret
[2019-10-14T21:41:13Z INFO  scylla::schematic::component] found image pull secret
[2019-10-14T21:41:13Z ERROR scylla] Error processing event: Error { inner:

ApiError AlreadyExists ("deployments.apps \"foo\" already exists") }
[2019-10-14T21:41:13Z INFO  scylla] Handled event
```

**Comment by technosophos** [comment] 2019-10-15 03:48
Here is the stack trace, and I can reconstruct at least part of what is going wrong:

```
[2019-10-15T03:41:16Z DEBUG rudr::schematic::traits::manual_scaler] params: {"replicaCount": Number(4)}
[2019-10-15T03:41:16Z INFO  rudr::instigator] Adding component nginx-replicated-v1
[2019-10-15T03:41:16Z INFO  rudr::schematic::component] Looking for image pull secret
[2019-10-15T03:41:16Z ERROR rudr] Error processing event: Error { inner: stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::hb3e9012d12460cbc (0x1029d881d)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h7972ff562d8bedb9 (0x1029d85ae)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
   2: failure::context::Context<D>::new::h48c8d2b1a9e934bb (0x102086481)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/context.rs:84
   3: <kube::Error as core::convert::From<kube::ErrorKind>>::from::h790aa8c4d4a48df6 (0x10209ad49)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.15.1/src/lib.rs:87
   4: kube::client::APIClient::request::hd7dc14033a5c3571 (0x101c3fa46)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.15.1/src/client/mod.rs:97
   5: kube::api::typed::Api<K>::create::h9fac6336dfe912b6 (0x101c90830)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.15.1/src/api/typed.rs:81
   6: rudr::workload_type::workload_builder::DeploymentBuilder::do_request::h6f12924b8b881520 (0x101d53705)
             at /Users/technosophos/Code/Rust/scylla/src/workload_type/workload_builder.rs:242
   7: <rudr::workload_type::server::ReplicatedServer as rudr::workload_type::WorkloadType>::add::h19c9e368464db5a8 (0x101c5a45e)
             at /Users/technosophos/Code/Rust/scylla/src/workload_type/server.rs:57
   8: rudr::workload_type::CoreWorkloadType::add::h96ecf924ad4c618f (0x101f67620)
             at /Users/technosophos/Code/Rust/scylla/src/workload_type.rs:91
   9: rudr::instigator::Instigator::exec::h516473617ee95fb8 (0x101d84378)
             at /Users/technosophos/Code/Rust/scylla/src/instigator.rs:296
  10: rudr::instigator::Instigator::modify::h71838df1618f3e8e (0x101d88768)
             at /Users/technosophos/Code/Rust/scylla/src/instigator.rs:412
  11: rudr::handle_event::h8e8da3183286b829 (0x101b7421b)
             at /Users/technosophos/Code/Rust/scylla/src/main.rs:178
  12: rudr::main::{{closure}}::h84f91310722ee781 (0x101c29e8a)
             at /Users/technosophos/Code/Rust/scylla/src/main.rs:100
  13: std::sys_common::backtrace::__rust_begin_short_backtrace::haf6da11fd8b6c875 (0x101c0f4e3)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/sys_common/backtrace.rs:77
  14: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h123dbcb8481ea64e (0x101ad3020)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/mod.rs:470
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h67b77d09e347604c (0x101a7c9a3)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:315
  16: std::panicking::try::do_call::ha36b3c1d89abc3ef (0x101a4c41f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  17: ___rust_maybe_catch_panic (0x102e0aeee)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libpanic_unwind/lib.rs:82
  18: std::panicking::try::ha6d7dbbb898fb6ef (0x101a4c091)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  19: std::panic::catch_unwind::hb20437959cf34f48 (0x101a7cb27)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  20: std::thread::Builder::spawn_unchecked::{{closure}}::hf090d64a12bf9064 (0x101ad2e6a)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/mod.rs:469
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}::haa718739d635c2a7 (0x101b5ca94)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha44ca87baccc45af (0x102df359d)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  23: std::sys::unix::thread::Thread::new::thread_start::hceb9fd3b79bf176c (0x102e0a45d)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  24: __pthread_body (0x7fff64e542ea)
  25: __pthread_start (0x7fff64e57248)

ApiError AlreadyExists ("deployments.apps \"scaled-repsvc\" already exists") }
[2019-10-15T03:41:17Z INFO  rudr] Handled event
```

The important lines are these:

```
   8: rudr::workload_type::CoreWorkloadType::add::h96ecf924ad4c618f (0x101f67620)
             at /Users/technosophos/Code/Rust/scylla/src/workload_type.rs:91
   9: rudr::instigator::Instigator::exec::h516473617ee95fb8 (0x101d84378)
             at /Users/technosophos/Code/Rust/scylla/src/instigator.rs:296
  10: rudr::instigator::Instigator::modify::h71838df1618f3e8e (0x101d88768)
             at /Users/technosophos/Code/Rust/scylla/src/instigator.rs:412
```

At 412, we are trying to _modify_ the Deployment. But when we go to 296, we're trying to _add_ a new deployment. I think that means this test is doing the wrong thing: https://github.com/oam-dev/rudr/blob/master/src/instigator.rs#L208-L212

Somehow, the test thinks that the deployment is a new object, so it is trying to create instead of patch. And that is leading to the error above.

/cc @wonderflow

**Comment by wonderflow** [comment] 2019-10-15 03:50
Let me fix it.

**Comment by technosophos** [comment] 2019-10-15 03:51
Okay. Thanks!

**Comment by wonderflow** [comment] 2019-10-15 10:33
I've tried many times and I couldn't reproduce this error. But I found the reason of #337.

**Comment by wonderflow** [comment] 2019-10-15 12:45
I have successfully reproduced this.
The main reason is interesting.

We have a status check loop, when we apply an AppConfig, the status check loop will check it and update the status of AppConfig. 
However, instigator haven't finished execute it yet, so the annotation used to distinguish whether the AppConfig has updated or not haven't added yet.
So when the status changed, another event happen and executed by the instigator. Then we meet the problem here, that resource is existed.

So I add a check in status loop, the status can't be updated when there's changes haven't done yet.
I think this issue can be fixed by that.

**Closed** 2019-10-15 15:12 UTC
Labels: Type: Bug
